[workspace]
resolver = "2"
members = [
  "backpressure-callee",
  "backpressure-caller",  
  "guest-async",
  "guest-sync",
  "guest-wait",
  "http-echo",
  "host",
  "http",
  "middleware",
  "poll",  
  "yield-callee",
  "yield-caller",
  "cancel-callee",
  "cancel-caller",
]
