[package]
name = "guest-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
once_cell = "1.19.0"
wit-bindgen = { git = "https://github.com/dicej/wit-bindgen", branch = "async" }

[lib]
crate-type = ["cdylib"]
